### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by yyds-xtt** [SidAg26/DRe-SCale#1]
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
我在运行这个代码的时候碰到了这个错误，没有Kubernetes 的config配置文件。怎么解决呢？

**Comment by SidAg26** [comment]
Usually, the config file for K8s can be found at ~/.kube/config that is configured while setting up the cluster where the method `config.load_kube_config` by default looks for. Alternatives to this can be - 

1. You may configure the environment variable `KUBECONFIG` with your file path e.g. `export KUBECONFIG=/path/to/your/kubeconfig`, OR, 
2. Pass the file path to your config file explicitly e.g. `config.load_kube_config('/path/to/your/kubeconfig')`

**Comment by yyds-xtt** [comment]
How do we build our own Kubernetes cluster? Isn't this very troublesome? Are there any ready-made environments for us to use?

**Comment by yyds-xtt** [comment]
I hope to design more efficient reinforcement learning algorithms, however, I have spent a lot of time on environment configuration. Can you recommend some convenient environments?

**Comment by SidAg26** [comment]
The framework that you are accessing in this project requires OpenFaaS for serverless functions that execute over K8s. Thus, you need to  - 

1. Setup a K8s cluster, either a [full deployment](https://github.com/SidAg26/certified-kubernetes-administrator) or any light-weight deployments such as [microK8s](https://github.com/SidAg26/ubuntu-microk8s-openfaas-setup)
2. Install OpenFaaS on top of it
3. Ensure that OpenFaaS functions can be deployed over K8s - a good reference can be found [here](https://github.com/openfaas/workshop) 

However, if you only intend to develop Reinforcement Learning (RL) algorithms irrespective of the practical setup, you may not need to deploy the cluster and take the RL algorithms as a reference and work in any other `Gymnasium` compatible environment.
